import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useTranslation, Trans } from "react-i18next"

export default function Home() {
  const { t, i18n } = useTranslation()
  const lngs: any = {
    en: {
      nativeName: "English"
    },
    de: {
      nativeName: "Deutsch"
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Multi Language</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {
            Object.keys(lngs).map(lng => (
              <button type='submit' key={lng} onClick={() => i18n.changeLanguage(lng)} disabled={i18n.resolvedLanguage === lng}>
                {lngs[lng].nativeName}
              </button>
            ))
          }
        </div>
        <p>
          <Trans i18nKey="description">
            Use this to learn how to code in next.js
          </Trans>
        </p>
        {
          t("learn")
        }
        <p>
          {
            t("new.key", "THis will be added automatically")
          }
        </p>
      </main>
    </div>
  )
}
